import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import HomePage from './HomePage'
import CountDownTimer from './CountdownTimer'
import PrayerTimes from './PrayerTimes'
import Navbar from './Navbar'
import Footer from './Footer'
import Programs from './Programs'
import Donate from './Donate'
import HeroPrograms from './HeroPrograms'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
  <script
    async
    src="https://js.stripe.com/v3/buy-button.js">
  </script>
      </Head>
      <main>
        <Navbar />
        
        <HomePage />
        <PrayerTimes />
        <Donate />
        <Programs />
        <Footer />
      </main>
    </>
  )
}
